
import Head from 'next/head'
import Image from 'next/image'
import {Container} from "react-bootstrap"

export default function Home() {
  return (
    <>
      <Head>
        <title>Miweb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>

        
      </Container>

    </>
  )
}
